Recreate security rules (ACL) when "clearing" GeoServer workspace
GeoCat/qgis-bridge-plugin pull request #175
Opened 2024-04-08 07:26 UTC by kannes

A quick implementation of https://github.com/GeoCat/qgis-bridge-plugin/issues/169. I bet I missed _something_ here as well :)

Upon workspace "clearing" (actually a deletion and creation of a new workspace) this:

1. Fetches existing ACL rules, e.g.:
```
existing_acl_rules={
  '*.*.r': '*',
  'test.*.r': 'ROLE_AUTHENTICATED',
  'test.*.w': 'ROLE_AUTHENTICATED,ROLE_LDAP_123',
  'foo.*.a': 'ROLE_OTHER',
  'foo.*.w': '*'
}
```

2. Extracts those that start with the workspace name and a dot (so that "foo2" won't be matched by "foo"), e.g.:
```
acl_rules={
  'test.*.r': 'ROLE_AUTHENTICATED',
  'test.*.w': 'ROLE_AUTHENTICATED,ROLE_LDAP_123'
}
```

3. Set those rules for the just re-created workspace.

-----

Fixes https://github.com/GeoCat/qgis-bridge-plugin/issues/169

2024-04-08 07:28 UTC, kannes commented
Will force push a clean history later, without the commit about isolation.

2024-04-08 17:07 UTC, GeoSander requested changes

2024-04-08 17:07 UTC, GeoSander commented on geocatbridge/servers/models/geoserver.py
>              stores = self.request(url).json()["dataStores"] or {}
Hi @kannes,

This has nothing to do with your work, but could you perhaps make this line a bit more robust while you are at it? Something like:

```suggestion
            stores = self.request(url).json().get("dataStores", {}) or {}
```

2024-04-10 13:12 UTC, GeoSander requested changes
Not sure where that `or {}` was coming from, as it doesn't make sense how it was implemented here. 
However, if the `dataStores` property exists but it's `null`, `get("dataStores", {})` will return `None`. So adding `or {}` in that case is just an extra safety measure to avoid errors in the next call on line 1047.
I never trust the GeoServer REST API responses (they sometimes return an empty string or null in some JSON responses), so I do like to see that added here. Sorry :)

2024-04-11 10:26 UTC, kannes commented
Ah, now I get it! Thanks for clarifying. I amended it to the last commit and force-pushed for a nice clean history :)

2024-04-15 09:58 UTC, GeoSander approved these changes
Looking good now, thanks @kannes!
Will merge.

2024-04-15 09:58 UTC, merged